services:
  # Backend API Service
  - type: web
    name: healthsync-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false # You'll set this in Render dashboard with PostgreSQL connection string
      - key: JWT_SECRET
        sync: false # You'll set this in Render dashboard
      - key: CORS_ORIGIN
        value: https://healthsync-frontend.onrender.com
    autoDeploy: true
    rootDir: .

  # Frontend Static Site
  - type: web
    name: healthsync-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s out -p $PORT
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://healthsync-backend.onrender.com/api
      - key: NODE_ENV
        value: production
    autoDeploy: true
    rootDir: .
